name: mobile
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.3.2 <4.0.0"
  flutter: 3.19.4

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter

dev_dependencies:
  custom_lint: ^0.6.4
  flutter_test:
    sdk: flutter
  leancode_lint: ^11.0.0

flutter:
  uses-material-design: true
