name: mobile
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: 3.19.0

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  go_router: ^13.2.1
  table_calendar: ^3.1.1

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.6.4
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.4.1
  leancode_lint: ^11.0.0

dependency_overrides:
  intl: ^0.18.1 # for table_calendar

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/map_styles/
