name: mobile
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: 3.19.0

dependencies:
  cloud_firestore: ^4.15.8
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  firebase_core: ^2.30.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  go_router: ^13.2.4
  provider: ^6.1.2
  table_calendar: ^3.1.1

dev_dependencies:
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  flutter_gen_runner: ^5.4.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.5.1
  leancode_lint: ^12.0.0

dependency_overrides:
  intl: ^0.18.1 # for table_calendar

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/answers/


flutter_gen:
  output: lib/resources





