name: prepare

on:
  workflow_dispatch:
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: mobile

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: mobile/pubspec.yaml

      - name: Download pub dependencies
        run: flutter pub get

      - name: Run analyzer
        run: |
          flutter analyze --no-fatal-infos
          dart run custom_lint

      - name: Run tests
        run: flutter test

      - name: dart format
        run: dart format --set-exit-if-changed .
